# See https://github.com/silverstripe/silverstripe-travis-support for setup details

language: php

sudo: false

matrix:
  include:
    - php: 5.4
      env: DB=PGSQL CORE_RELEASE=3.1
    - php: 5.5
      env: DB=MYSQL CORE_RELEASE=3.2
    - php: 5.6
      env: DB=MYSQL CORE_RELEASE=3.3 SUBSITES=1
    - php: 5.6
      env: DB=MYSQL CORE_RELEASE=3.3 QUEUEDJOBS=1
    - php: 7.1
      env: DB=MYSQL CORE_RELEASE=3.6
    - php: 7.1
      env: DB=MYSQL CORE_RELEASE=3

before_script:
  - composer self-update || true
  - git clone git://github.com/silverstripe/silverstripe-travis-support.git ~/travis-support
  - "if [ \"$SUBSITES\" = \"\" -a \"$QUEUEDJOBS\" = \"\" ]; then php ~/travis-support/travis_setup.php --source `pwd` --target ~/builds/ss; fi"
  - "if [ \"$SUBSITES\" = \"1\" ]; then php ~/travis-support/travis_setup.php --source `pwd` --target ~/builds/ss --require silverstripe/subsites; fi"
  - "if [ \"$QUEUEDJOBS\" = \"1\" ]; then php ~/travis-support/travis_setup.php --source `pwd` --target ~/builds/ss --require silverstripe/queuedjobs; fi"
  - cd ~/builds/ss

script:
  - vendor/bin/phpunit fulltextsearch/tests/
